# Generated by Django 5.1.7 on 2025-03-17 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('offerprice', models.IntegerField()),
                ('color', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='product/')),
                ('image1', models.ImageField(default='', upload_to='product/')),
                ('image2', models.ImageField(default='', upload_to='product/')),
                ('image3', models.ImageField(default='', upload_to='product/')),
                ('image4', models.ImageField(default='', upload_to='product/')),
                ('image5', models.ImageField(default='', upload_to='product/')),
                ('size', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('priority', models.IntegerField(default=0)),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShoeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('totalprice', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loftapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shoe_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loftapp.shoecategory'),
        ),
    ]
