# Generated by Django 5.2 on 2025-04-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loftapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='totalprice',
            field=models.IntegerField(default=0),
        ),
    ]
