# Generated by Django 5.2 on 2025-04-15 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loftapp', '0002_alter_cart_totalprice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('status', models.CharField(default='Pending', max_length=254, verbose_name='Payment Status')),
                ('provider_order_id', models.CharField(max_length=40, null=True, verbose_name='Order ID')),
                ('payment_id', models.CharField(max_length=36, null=True, verbose_name='Payment ID')),
                ('signature_id', models.CharField(max_length=128, null=True, verbose_name='Signature ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loftapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
